### ISSUE TITLE
Set default colormap in recipe settings

### ISSUE THREAD

**Issue by MirjamSchr** [tillbiskup/aspecd#1]
It would be great if you could set the default colormap already in the main settings of the recipe.

I imagine something like this: 
```
format:
  type: ASpecD recipe
  version: '0.2'
settings:
  default_package: aspecd
  default_colormap: turbo
datasets:
  - [...]
```
