### ISSUE TITLE
Filtered data cannot be sorted

### ISSUE THREAD

**Issue by MirjamSchr** [tillbiskup/aspecd#2]
After applying a (Savitzky-Golay) filter to the dataset, the resulting data is consistently plotted at the bottom of the list of datasets, preventing manual sorting of the figure. 

When having the following recipe: 

```
  - kind: processing
    type: Filtering
    properties:
      parameters:
        type: savgol
        window_length: 100
        order: 2
    apply_to: 
      - dataset3
      - dataset4
    result: 
      - dataset3-filtered
      - dataset4-filtered
  - kind: multiplot
    type: MultiPlotter1DStacked
    apply_to:
      - dataset1
      - dataset3-filtered
      - dataset2
      - dataset4-filtered
```

the order in the resulting figure is: 

  - dataset1
  - dataset2
  - dataset3
  - dataset4
