### ISSUE TITLE
List of titles is not possible.

### ISSUE THREAD

**Issue by MirjamSchr** [tillbiskup/aspecd#4]
Not sure if feature or bug, but it is not possible, to assign different titles in a series of figures in one plot-task. 

I would like to do it like that:
```
  - kind: singleplot
    type: FittingPlotter2D
    properties:
      properties:
        figure:
          title: 
            - title1
            - title2
  apply_to: 
    - dataset1
    - dataset2
```
Currently, the list is used as a title.
