### ISSUE TITLE
Location of plotannotation (text) to be given as relative position of the figure

### ISSUE THREAD

**Issue by MirjamSchr** [tillbiskup/aspecd#8]
I would appreciate, that one could give the position of a plotannotation as relative position on the figure. I think of giving the number as percentage, such that annotations are in the same position even if the scaling of the axes is very different. 

The recipe might look as follows: 
```
  - kind: plotannotation
    type: Text
    properties:
      parameters:
        positions:
          - [5, 95]  # translates to the upper left corner (5% of the width, 95% of the height)
        position_unit: percent  # could be axis or even index
        texts:
          - A
    plotter: 
      - my_spectrum
```

Depending on where the origin of the figure coordinate is, the percentages are different. I thought of it being bottom left.
